services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./db:/data/db
 
  snack-shop-be:
    build: ../snack-shop-be
    restart: always
    ports: 
      - '8080:8080'
    depends_on:
      - mongodb

  snack-shop-bff:
    build: ../snack-shop-bff
    restart: always
    ports: 
      - '3000:3000'
    environment:
      - SNACK_SHOP_BE_URL=http://snack-shop-be:8080/
    depends_on:
      - snack-shop-be

  snack-shop-fe:
    build: ../snack-shop-fe
    restart: always
    ports: 
      - '9090:9090'
    environment:
      - SNACK_SHOP_BFF_URL=http://snack-shop-bff:3000/ # TODO: Use this in the FE
    depends_on:
      - snack-shop-bff
  
  stock-snacks:
    build: ../dev
    restart: no
    environment:
      - SNACK_API_ENDPOINT=http://snack-shop-be:8080/api/snacks
    depends_on:
      - snack-shop-be